# Prometheus Configuration for UUID Authorization System Monitoring
# Production-ready configuration with comprehensive metric collection

global:
  scrape_interval: 15s     # Set the scrape interval to every 15 seconds.
  evaluation_interval: 15s # Evaluate rules every 15 seconds.
  
  external_labels:
    cluster: 'velro-production'
    environment: 'production'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - "alert_rules.yml"
  - "recording_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'velro-backend'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 5s  # High-frequency scraping for authorization metrics
    scrape_timeout: 10s
    metrics_path: '/metrics'
    honor_labels: true
    
    # Scrape configuration for authorization system
    relabel_configs:
      - source_labels: [__name__]
        regex: 'velro_auth_.*'
        target_label: 'service'
        replacement: 'authorization'
      
      - source_labels: [__name__]
        regex: 'velro_cache_.*'
        target_label: 'service'
        replacement: 'cache'
      
      - source_labels: [__name__]
        regex: 'velro_security_.*'
        target_label: 'service'
        replacement: 'security'

  # Redis monitoring for cache performance
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Database metrics (PostgreSQL)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s
    scrape_timeout: 10s

  # Application health checks
  - job_name: 'velro-health'
    static_configs:
      - targets: ['localhost:8000']
    scrape_interval: 30s
    scrape_timeout: 10s
    metrics_path: '/health'
    
  # Kong API Gateway metrics (if available)
  - job_name: 'kong-metrics'
    static_configs:
      - targets: ['kong:8001']
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: '/metrics'
    
  # Self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    scrape_timeout: 10s

# Storage configuration
storage:
  tsdb:
    path: /prometheus/data
    retention.time: 15d
    retention.size: 10GB
    
# Web configuration
web:
  console.templates: /etc/prometheus/consoles
  console.libraries: /etc/prometheus/console_libraries
  enable-admin-api: true
  enable-lifecycle: true
  
# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: 'https://your-metrics-store/api/v1/write'
#     basic_auth:
#       username: 'metrics_user'
#       password: 'metrics_password'